# Generated by Django 5.0.1 on 2024-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('title_description', models.CharField(max_length=200, verbose_name='One title about the hotel')),
                ('embed_link', models.CharField(max_length=200, verbose_name='Link for google maps')),
                ('rating', models.IntegerField(default=1, verbose_name='Hotel Rating(Max. 10)')),
                ('cover_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Cover Photo')),
                ('price', models.IntegerField(default=1, verbose_name='Price')),
                ('comment_quantity', models.IntegerField(default=1, verbose_name='Number of comments')),
                ('amenities', models.CharField(max_length=200, verbose_name='Enter the amenities.(split with ,)')),
            ],
        ),
    ]
