# Generated by Django 5.0.1 on 2024-01-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotels_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='title_description',
            field=models.TextField(verbose_name='One title about the hotel'),
        ),
    ]
