# Generated by Django 5.0.1 on 2024-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotels_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='embed_link',
            field=models.TextField(verbose_name='Link for google maps'),
        ),
    ]
