# Generated by Django 5.0.1 on 2024-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotels_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='discounted_price',
            field=models.IntegerField(default=1, verbose_name='Price'),
        ),
    ]
