# Generated by Django 5.0.1 on 2024-01-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotels_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='discounted_price',
            field=models.IntegerField(default=1, verbose_name='Discounted Price'),
        ),
    ]
